/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface NativeRenderResult {
  html: string
  hash: string
  nodeCount: number
  bytes: number
}

export declare function renderJson(documentJson: string, optionsJson?: string | undefined | null): NativeRenderResult
